### ISSUE TITLE
Unclear what edm4hep::ReconstructedParticle::type should be

### ISSUE THREAD

**Issue by DraTeots** [key4hep/EDM4hep#183]
On schema yaml file it is said

```yaml
edm4hep::ReconstructedParticle:
    Description: "Reconstructed Particle"
    Author : "F.Gaede, DESY"
    Members:
      - int32_t type //type of reconstructed particle. Check/set collection parameters ReconstructedParticleTypeNames and ReconstructedParticleTypeValues.
```

But there is no definition of ReconstructedParticleTypeNames nor ReconstructedParticleTypeValues. Unable to find any indication of how this type field should be set and what is the convention
