### ISSUE TITLE
Names of association types

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#344]
This is a discussion issue for settling the naming of the association types in EDM4hep. The names should be valid even after templated associations (https://github.com/AIDASoft/podio/pull/257) are available. To facilitate decision making, I will put dedicated questions into comments, which can then be voted on via either :+1: or :-1:. Feel free to add more questions if necessary.

As a brief overview, currently we have the following association types. In the following I assume that we have adopted the naming convention for `from` and `to` that is proposed in #341)

| name | from | to |
|--|--|--|
| `MCRecoParticleAssociation` | `ReconstructedParticle` | `MCParticle` |
| `MCRecoCaloAssociation` | `CalorimeterHit` | `SimCalorimeterHit` |
| `MCRecoTrackerAssociation` | `TrackerHit` | `SimTrackerHit` |
| `MCRecoCaloParticleAssociation` | `CalorimeterHit` | `MCParticle` |
| `MCRecoClusterParticleAssociation` | `Cluster` | `MCParticle` | 
| `MCRecoTrackParticleAssociation` | `Track` | `MCParticle` |
| `RecoParticleVertexAssociation` | `Vertex` | `ReconstructedParticle` |

#341 would give all of these an expilcit direction. Once we have https://github.com/AIDASoft/podio/pull/257 available, this direction would become much more implicit because people can do something like

```cpp
auto assoc = MCRecoParticleAssociation{};
auto mc = assoc.get<MCParticle>();
auto rec = assoc.get<ReconstructedParticle>();
```

If we want to keep the explicit directions meaningful we would need to introduce associations for both directions. (Note that previously we didn't need to do this, because `from` and `to` were `sim` and `rec`, so there was no explicit direction).

Tagging a few people for enagagement: @gaede @jmcarcell @BrieucF @andresailer @Zehvogel @hegner

**Comment by tmadlener** [comment]
Should we have associations that have explicit directions in both directions? E.g. have an (equivalent of)
```yaml
edm4hep::MCRecoParticleAssociation:
  OneToOneRelations:
    - MCParticle from
    - ReconstructedParticle to

edm4hep::RecoMCParticleAssociation:
  OneToOneRelations:
    - ReconstructedParticle from
    - MCParticle to
```
