### ISSUE TITLE
Rework the generator information related datatypes

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#409]
The existing `GeneratorPdfInfo` and `GeneratorInfoParameters` should be merged and slightly decluttered. This is the result of a discussion between generator experts and @dirkzerwas, @gaede and @tmadlener.

Given that this is only used in k4GeneratorsConfig at the moment, we will make this a breaking change without too many considerations for backwards compatibility.

**Comment by tmadlener** [comment]
The proposed layout for the final result should be something along the lines of

```yaml
edm4hep::GeneratorEventParameters:  # Or GenEventHeader(?)
  Members:
    - double sqrts [GeV]          // sqrt(s) - nominal beam center of mass energy
    - double beamPz0 [GeV]  // nominal z-momentum of incoming particle beam
    - double beamPz1 [GeV]  // nominal z-momentum of incoming particle beam
    - std::array<int, 2> partonId // PDG id if the partons undergoing the hard scatter
  VectorMembers:
    - double crossSections [pb] // List of cross sections
    - double crossSectionErrors [pb] // List of cross section errors
    - double weights // event weights
```

The PDF related information can in principle be dropped without substitution since PDF reweighting only works for LO. For NLO (and up) this is all done on the fly and encoded into event weights. The event weights currently live in the `edm4hep::EventHeader`, but should arguably be in this structure, since the `EventHeader` should ideally be usable for recorded data without weights. I am not yet sure whether we want to go that way.

An open question is whether we want to also the link to the partons as `edm4hep::MCParticle`s here, such that the actual beam energies (after bremsstrahlung, ISR, etc.) can be easily retrieved / calculated from them.
- [ ] How does Belle II store this information?

Additional possible fields could be the number of trials the generator needed for an event and the maximum observed weight.
